/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "accent": "#c26d4d",
        "accent-soft": "#e4b8a8",
        "secondary": "#006d43",
        "on-secondary-container": "#007147",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#cfe5ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#78fbb6",
        "on-primary-fixed-variant": "#004a79",
        "on-secondary-fixed": "#002111",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-secondary-fixed-variant": "#005232",
        "on-primary-fixed": "#001d34",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#0d1c2e",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "on-surface-variant": "#404751",
        "secondary-container": "#75f8b3",
        "tertiary": "#4c5b6f",
        "primary-fixed-dim": "#9acbff",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#f7f8ff",
        "inverse-primary": "#9acbff",
        "on-primary-container": "#f7f9ff",
        "on-error": "#ffffff",
        "surface-tint": "#00629e",
        "outline-variant": "#c0c7d2",
        "surface": "#f7f9fb",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "tertiary-container": "#657388",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#b9c7df",
        "primary": "#005e97",
        "on-primary": "#ffffff",
        "outline": "#707882",
        "tertiary-fixed": "#d5e3fc",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#0077be",
        "secondary-fixed-dim": "#59de9b",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
